-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_versions
(
    version_id serial NOT NULL,
    version_string character varying(50) COLLATE pg_catalog."default" NOT NULL,
    build_date date,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT app_versions_pkey PRIMARY KEY (version_id),
    CONSTRAINT app_versions_version_string_key UNIQUE (version_string)
);

COMMENT ON TABLE public.app_versions
    IS 'Версии тестируемого приложения';

COMMENT ON COLUMN public.app_versions.version_string
    IS 'Семантическая версия (формат: X.Y.Z)';

CREATE TABLE IF NOT EXISTS public.audit_log
(
    audit_id bigserial NOT NULL,
    table_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    operation character varying(10) COLLATE pg_catalog."default" NOT NULL,
    record_id integer NOT NULL,
    user_id integer,
    changed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    old_values jsonb,
    new_values jsonb,
    ip_address inet,
    CONSTRAINT audit_log_pkey PRIMARY KEY (audit_id)
);

COMMENT ON TABLE public.audit_log
    IS 'Журнал аудита изменений данных';

CREATE TABLE IF NOT EXISTS public.autotest_versions
(
    version_id serial NOT NULL,
    autotest_id integer NOT NULL,
    version_string character varying(50) COLLATE pg_catalog."default" NOT NULL,
    commit_hash character varying(64) COLLATE pg_catalog."default",
    change_description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT autotest_versions_pkey PRIMARY KEY (version_id),
    CONSTRAINT uq_autotest_version UNIQUE (autotest_id, version_string)
);

COMMENT ON TABLE public.autotest_versions
    IS 'Версии автотестов (версионирование кода)';

COMMENT ON COLUMN public.autotest_versions.commit_hash
    IS 'Хеш коммита из системы контроля версий (Git)';

CREATE TABLE IF NOT EXISTS public.autotests
(
    autotest_id serial NOT NULL,
    test_case_id integer NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    owner_user_id integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    CONSTRAINT autotests_pkey PRIMARY KEY (autotest_id),
    CONSTRAINT autotests_name_key UNIQUE (name)
);

COMMENT ON TABLE public.autotests
    IS 'Автоматизированные тесты (код)';

CREATE TABLE IF NOT EXISTS public.config_errors
(
    config_error_id serial NOT NULL,
    env_config_id integer NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    detected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    severity_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    resolved_at timestamp with time zone,
    resolved_by integer,
    CONSTRAINT config_errors_pkey PRIMARY KEY (config_error_id)
);

COMMENT ON TABLE public.config_errors
    IS 'Журнал ошибок конфигурации окружений';

CREATE TABLE IF NOT EXISTS public.env_config_params
(
    env_config_param_id serial NOT NULL,
    env_config_id integer NOT NULL,
    key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default",
    is_sensitive boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT env_config_params_pkey PRIMARY KEY (env_config_param_id),
    CONSTRAINT uq_envconfigparams UNIQUE (env_config_id, key)
);

COMMENT ON TABLE public.env_config_params
    IS 'Параметры конфигурации окружения (ключ-значение)';

COMMENT ON COLUMN public.env_config_params.is_sensitive
    IS 'Признак конфиденциальных данных (пароли, API-ключи)';

CREATE TABLE IF NOT EXISTS public.env_configs
(
    env_config_id serial NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description character varying(500) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    CONSTRAINT env_configs_pkey PRIMARY KEY (env_config_id),
    CONSTRAINT env_configs_name_key UNIQUE (name)
);

COMMENT ON TABLE public.env_configs
    IS 'Конфигурации тестовых окружений (DEV, QA, STAGING, PROD)';

CREATE TABLE IF NOT EXISTS public.goose_db_version
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT goose_db_version_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.priorities
(
    priority_id serial NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rank smallint NOT NULL,
    color_hex character varying(7) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT priorities_pkey PRIMARY KEY (priority_id),
    CONSTRAINT priorities_code_key UNIQUE (code)
);

COMMENT ON TABLE public.priorities
    IS 'Справочник приоритетов тестовых случаев и планов';

COMMENT ON COLUMN public.priorities.rank
    IS 'Уровень важности от 1 (низкий) до 5 (критический)';

CREATE TABLE IF NOT EXISTS public.report_templates
(
    template_id serial NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    template_content text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT report_templates_pkey PRIMARY KEY (template_id),
    CONSTRAINT report_templates_name_key UNIQUE (name)
);

COMMENT ON TABLE public.report_templates
    IS 'Шаблоны отчетов о качестве';

CREATE TABLE IF NOT EXISTS public.reports
(
    report_id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    template_id integer NOT NULL,
    owner_user_id integer NOT NULL,
    report_content text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reports_pkey PRIMARY KEY (report_id)
);

COMMENT ON TABLE public.reports
    IS 'Отчеты о качестве продукта';

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id serial NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    access_level smallint NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT roles_code_key UNIQUE (code)
);

COMMENT ON TABLE public.roles
    IS 'Справочник ролей пользователей в системе';

COMMENT ON COLUMN public.roles.access_level
    IS 'Уровень доступа: 1-минимальный (Guest), 10-максимальный (Administrator)';

CREATE TABLE IF NOT EXISTS public.statuses
(
    status_id serial NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category character varying(50) COLLATE pg_catalog."default",
    is_final boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT statuses_pkey PRIMARY KEY (status_id),
    CONSTRAINT statuses_code_key UNIQUE (code)
);

COMMENT ON TABLE public.statuses
    IS 'Универсальный справочник статусов';

COMMENT ON COLUMN public.statuses.is_final
    IS 'Признак финального статуса (не подлежит изменению)';

CREATE TABLE IF NOT EXISTS public.test_case_steps
(
    step_id serial NOT NULL,
    test_case_id integer NOT NULL,
    step_order integer NOT NULL,
    action_text text COLLATE pg_catalog."default" NOT NULL,
    expected_result text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT test_case_steps_pkey PRIMARY KEY (step_id),
    CONSTRAINT uq_testcasesteps UNIQUE (test_case_id, step_order)
);

COMMENT ON TABLE public.test_case_steps
    IS 'Шаги выполнения тестовых случаев';

CREATE TABLE IF NOT EXISTS public.test_cases
(
    test_case_id serial NOT NULL,
    priority_id integer NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    owner_user_id integer NOT NULL,
    is_automated boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    estimated_duration_minutes integer,
    CONSTRAINT test_cases_pkey PRIMARY KEY (test_case_id),
    CONSTRAINT test_cases_name_key UNIQUE (name)
);

COMMENT ON TABLE public.test_cases
    IS 'Тестовые случаи (ручные и автоматизированные)';

CREATE TABLE IF NOT EXISTS public.test_plans
(
    test_plan_id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    priority_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    acceptance_criteria text COLLATE pg_catalog."default",
    owner_user_id integer NOT NULL,
    version_no integer NOT NULL DEFAULT 1,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DRAFT'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    CONSTRAINT test_plans_pkey PRIMARY KEY (test_plan_id),
    CONSTRAINT test_plans_name_key UNIQUE (name)
);

COMMENT ON TABLE public.test_plans
    IS 'Планы тестирования';

CREATE TABLE IF NOT EXISTS public.test_result_artifacts
(
    artifact_id serial NOT NULL,
    test_result_id integer NOT NULL,
    kind character varying(50) COLLATE pg_catalog."default" NOT NULL,
    file_path text COLLATE pg_catalog."default",
    file_size_bytes bigint,
    mime_type character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT test_result_artifacts_pkey PRIMARY KEY (artifact_id)
);

COMMENT ON TABLE public.test_result_artifacts
    IS 'Артефакты выполнения тестов (скриншоты, логи, видео)';

CREATE TABLE IF NOT EXISTS public.test_results
(
    test_result_id serial NOT NULL,
    run_item_id integer NOT NULL,
    status_id integer NOT NULL,
    executor_user_id integer,
    execution_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result_summary character varying(1000) COLLATE pg_catalog."default",
    execution_duration_minutes integer,
    error_message text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT test_results_pkey PRIMARY KEY (test_result_id)
);

COMMENT ON TABLE public.test_results
    IS 'Результаты выполнения тестов';

COMMENT ON COLUMN public.test_results.execution_duration_minutes
    IS 'Фактическое время выполнения в минутах';

CREATE TABLE IF NOT EXISTS public.test_run_items
(
    run_item_id serial NOT NULL,
    test_run_id integer NOT NULL,
    test_case_id integer NOT NULL,
    execution_order integer,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT test_run_items_pkey PRIMARY KEY (run_item_id),
    CONSTRAINT uq_testrunitems UNIQUE (test_run_id, test_case_id)
);

COMMENT ON TABLE public.test_run_items
    IS 'Тест-кейсы, включенные в тестовый прогон';

CREATE TABLE IF NOT EXISTS public.test_runs
(
    test_run_id serial NOT NULL,
    test_plan_id integer NOT NULL,
    env_config_id integer NOT NULL,
    tool_config_id integer NOT NULL,
    version_id integer NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PLANNED'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    CONSTRAINT test_runs_pkey PRIMARY KEY (test_run_id),
    CONSTRAINT test_runs_name_key UNIQUE (name)
);

COMMENT ON TABLE public.test_runs
    IS 'Прогоны тестирования';

CREATE TABLE IF NOT EXISTS public.tool_config_params
(
    tool_config_param_id serial NOT NULL,
    tool_config_id integer NOT NULL,
    key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default",
    is_sensitive boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tool_config_params_pkey PRIMARY KEY (tool_config_param_id),
    CONSTRAINT uq_toolconfigparams UNIQUE (tool_config_id, key)
);

COMMENT ON TABLE public.tool_config_params
    IS 'Параметры конфигурации инструментов (ключ-значение)';

CREATE TABLE IF NOT EXISTS public.tool_configs
(
    tool_config_id serial NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description character varying(500) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    CONSTRAINT tool_configs_pkey PRIMARY KEY (tool_config_id),
    CONSTRAINT tool_configs_name_key UNIQUE (name)
);

COMMENT ON TABLE public.tool_configs
    IS 'Конфигурации инструментов автотестирования (Selenium, Playwright, Jest)';

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    granted_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by integer,
    valid_until timestamp with time zone,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

COMMENT ON TABLE public.user_roles
    IS 'Связь пользователей с ролями (многие-ко-многим)';

COMMENT ON COLUMN public.user_roles.valid_until
    IS 'Дата окончания действия роли (NULL = бессрочно)';

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(200) COLLATE pg_catalog."default",
    full_name character varying(200) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    last_login timestamp with time zone,
    failed_login_attempts integer NOT NULL DEFAULT 0,
    account_locked_until timestamp with time zone,
    password_changed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

COMMENT ON TABLE public.users
    IS 'Пользователи системы тестирования';

COMMENT ON COLUMN public.users.password_hash
    IS 'Хеш пароля (bcrypt/argon2/scram-sha-256)';

COMMENT ON COLUMN public.users.failed_login_attempts
    IS 'Счетчик неудачных попыток входа';

ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT fk_audit_log_to_users FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.autotest_versions
    ADD CONSTRAINT fk_autotest_versions_to_autotests FOREIGN KEY (autotest_id)
    REFERENCES public.autotests (autotest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.autotests
    ADD CONSTRAINT fk_autotests_to_test_cases FOREIGN KEY (test_case_id)
    REFERENCES public.test_cases (test_case_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.config_errors
    ADD CONSTRAINT fk_config_errors_to_env_configs FOREIGN KEY (env_config_id)
    REFERENCES public.env_configs (env_config_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.env_config_params
    ADD CONSTRAINT fk_env_config_params_to_env_configs FOREIGN KEY (env_config_id)
    REFERENCES public.env_configs (env_config_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_envconfigparams_sensitive
    ON public.env_config_params(env_config_id);


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT fk_reports_to_report_templates FOREIGN KEY (template_id)
    REFERENCES public.report_templates (template_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_reports_template
    ON public.reports(template_id);


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT fk_reports_to_users FOREIGN KEY (owner_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_reports_owner
    ON public.reports(owner_user_id);


ALTER TABLE IF EXISTS public.test_case_steps
    ADD CONSTRAINT fk_test_case_steps_to_test_cases FOREIGN KEY (test_case_id)
    REFERENCES public.test_cases (test_case_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.test_cases
    ADD CONSTRAINT fk_test_cases_to_priorities FOREIGN KEY (priority_id)
    REFERENCES public.priorities (priority_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_testcases_priority
    ON public.test_cases(priority_id);


ALTER TABLE IF EXISTS public.test_cases
    ADD CONSTRAINT fk_test_cases_to_users_owner FOREIGN KEY (owner_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_testcases_owner
    ON public.test_cases(owner_user_id);


ALTER TABLE IF EXISTS public.test_plans
    ADD CONSTRAINT fk_test_plans_to_users_owner FOREIGN KEY (owner_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_testplans_owner
    ON public.test_plans(owner_user_id);


ALTER TABLE IF EXISTS public.test_result_artifacts
    ADD CONSTRAINT fk_test_result_artifacts_to_test_results FOREIGN KEY (test_result_id)
    REFERENCES public.test_results (test_result_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_testresultartifacts_result
    ON public.test_result_artifacts(test_result_id);


ALTER TABLE IF EXISTS public.test_results
    ADD CONSTRAINT fk_test_results_to_statuses FOREIGN KEY (status_id)
    REFERENCES public.statuses (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_testresults_status
    ON public.test_results(status_id);


ALTER TABLE IF EXISTS public.test_results
    ADD CONSTRAINT fk_test_results_to_test_run_items FOREIGN KEY (run_item_id)
    REFERENCES public.test_run_items (run_item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_testresults_runitem
    ON public.test_results(run_item_id);


ALTER TABLE IF EXISTS public.test_results
    ADD CONSTRAINT fk_test_results_to_users_tester FOREIGN KEY (executor_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_testresults_executor
    ON public.test_results(executor_user_id);


ALTER TABLE IF EXISTS public.test_run_items
    ADD CONSTRAINT fk_test_run_items_to_test_cases FOREIGN KEY (test_case_id)
    REFERENCES public.test_cases (test_case_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_testrunitems_testcase
    ON public.test_run_items(test_case_id);


ALTER TABLE IF EXISTS public.test_run_items
    ADD CONSTRAINT fk_test_run_items_to_test_runs FOREIGN KEY (test_run_id)
    REFERENCES public.test_runs (test_run_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_testrunitems_testrun
    ON public.test_run_items(test_run_id);


ALTER TABLE IF EXISTS public.test_runs
    ADD CONSTRAINT fk_test_runs_to_env_configs FOREIGN KEY (env_config_id)
    REFERENCES public.env_configs (env_config_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_testruns_envconfig
    ON public.test_runs(env_config_id);


ALTER TABLE IF EXISTS public.test_runs
    ADD CONSTRAINT fk_test_runs_to_test_plans FOREIGN KEY (test_plan_id)
    REFERENCES public.test_plans (test_plan_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_testruns_testplan
    ON public.test_runs(test_plan_id);


ALTER TABLE IF EXISTS public.test_runs
    ADD CONSTRAINT fk_test_runs_to_users_created_by FOREIGN KEY (created_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.tool_config_params
    ADD CONSTRAINT fk_tool_config_params_to_tool_configs FOREIGN KEY (tool_config_id)
    REFERENCES public.tool_configs (tool_config_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_user_roles_granted_by FOREIGN KEY (granted_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_user_roles_to_roles FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_user_roles_to_users FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;